DROP DATABASE IF EXISTS GROCERY_TECH;
CREATE DATABASE GROCERY_TECH;
use GROCERY_TECH;


CREATE TABLE ADDRESSES
(address_id INT(2) NOT NULL,
 street VARCHAR(64) NOT NULL,
 zipcode INT(5) NOT NULL,
 state VARCHAR(16) NOT NULL,
 city VARCHAR(16) NOT NULL,
 house_number VARCHAR(4) NOT NULL,
 PRIMARY KEY(address_id)
) Engine=InnoDB;

CREATE TABLE USER
(first_name VARCHAR(16),
 last_name VARCHAR(16),
 username VARCHAR(32) NOT NULL,
 password VARCHAR(32) NOT NULL,
 user_type VARCHAR(16) NOT NULL,
 email VARCHAR(32) NOT NULL,
 PRIMARY KEY(username)) Engine=InnoDB;

CREATE TABLE MANAGES
(manager_username VARCHAR(32) NOT NULL,
 store_address INT(2) NOT NULL,
 PRIMARY KEY(manager_username, store_address),
 FOREIGN KEY(manager_username) REFERENCES USER(username) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY(store_address) REFERENCES ADDRESSES(address_id) ON UPDATE CASCADE ON DELETE CASCADE
) Engine=InnoDB;

CREATE TABLE BUYER
(username VARCHAR(32) NOT NULL,
 address_id VARCHAR(2) NOT NULL,
 phone CHAR(10) NOT NULL,
 default_payment VARCHAR(16) NOT NULL,
 PRIMARY KEY(username),
 FOREIGN KEY(username) REFERENCES USER(username) ON UPDATE CASCADE ON DELETE CASCADE
) Engine=InnoDB;

CREATE TABLE PAYMENTS
(username VARCHAR(32) NOT NULL,
 payment_name VARCHAR(16) NOT NULL,
 account_number  CHAR(9) NOT NULL,
 routing_number CHAR(9) NOT NULL,
 PRIMARY KEY(username),
 FOREIGN KEY(username) REFERENCES BUYER(username)
) Engine=InnoDB;

CREATE TABLE GROCERY_STORE
(phone CHAR(10),
 opening_time TIME NOT NULL,
 closing_time TIME NOT NULL,
 store_name  VARCHAR(16) NOT NULL,
 address_id INT(2) NOT NULL,
 PRIMARY KEY(store_name, address_id),
 FOREIGN KEY(address_id) REFERENCES ADDRESSES(address_id) ON UPDATE CASCADE ON DELETE CASCADE
) Engine=InnoDB;

CREATE TABLE ITEM
(item_name VARCHAR(32) NOT NULL,
 food_group VARCHAR(16) NOT NULL,
 exp_date  DATE,
 quantity INT(2) NOT NULL,
 item_id INT(2) NOT NULL,
 listed_price DECIMAL(4,2) NOT NULL,
 wholesale_price DECIMAL(4,2) NOT NULL,
 description VARCHAR(256) NOT NULL,
 PRIMARY KEY(item_id)
) Engine=InnoDB;

CREATE TABLE SOLD_AT
(
 item_id INT(2) NOT NULL,
 store_address INT(2) NOT NULL,
 in_stock BOOLEAN NOT NULL,
 PRIMARY KEY(item_id, store_address),
 FOREIGN KEY(item_id) REFERENCES ITEM(item_id) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY(store_address) REFERENCES ADDRESSES(address_id) ON UPDATE CASCADE ON DELETE CASCADE
) Engine=InnoDB;

CREATE TABLE ORDERR
(
 delivery_instructions VARCHAR(256) NOT NULL,
 order_id INT(5) NOT NULL,
 delivery_date DATE NOT NULL,
 PRIMARY KEY(order_id)
) Engine=InnoDB;

CREATE TABLE SELECT_ITEM
(item_id INT(2) NOT NULL,
 order_id INT(5) NOT NULL,
 quantity INT(2) NOT NULL,
 PRIMARY KEY(item_id, order_id),
 FOREIGN KEY(item_id) REFERENCES ITEM(item_id) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY(order_id) REFERENCES ORDERR(order_id) ON UPDATE CASCADE ON DELETE CASCADE
) Engine=InnoDB;


CREATE TABLE SYSTEM_INFO
(system_id INT(1) NOT NULL,
 user_codes CHAR(9) NOT NULL,
 PRIMARY KEY(system_id)
) Engine=InnoDB;


CREATE TABLE ORDERED_BY
(
order_id INT(5) NOT NULL,
buyer_username VARCHAR(32) NOT NULL,
PRIMARY KEY(order_id, buyer_username),
FOREIGN KEY(order_id) REFERENCES ORDERR(order_id) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(buyer_username) REFERENCES BUYER(username) ON UPDATE CASCADE ON DELETE CASCADE
) Engine=InnoDB;

CREATE TABLE ORDER_FROM
(
store_address INT(2) NOT NULL,
order_id INT(5) NOT NULL,
PRIMARY KEY(order_id, store_address),
FOREIGN KEY(order_id) REFERENCES ORDERR(order_id) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(store_address) REFERENCES ADDRESSES(address_id) ON UPDATE CASCADE ON DELETE CASCADE
) Engine=InnoDB;

CREATE TABLE DELIVERED_BY
(
order_id INT(5) NOT NULL,
deliverer_username VARCHAR(32) NOT NULL,
delivery_time TIME NOT NULL,
isDelivered BOOLEAN NOT NULL,
PRIMARY KEY(order_id, deliverer_username),
FOREIGN KEY(order_id) REFERENCES ORDERR(order_id) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(deliverer_username) REFERENCES USER(username) ON UPDATE CASCADE ON DELETE CASCADE
) Engine=InnoDB;